# Generated by Django 5.2.1 on 2025-05-11 20:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsapp', '0003_site_visitor_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='visitor',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='visitor_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
